import Navbar from "./components/navbar";
import footer from "./components/footer";
import "./globals.css";




export const metadata = {
  title: "project",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Navbar/>
        <main className="min-h-screen">
        {children}
        </main>
      <footer/>
      </body>
    </html>
  );
}
